version: "3.7"

services:
  mcserver:
    build: .
    image: mc-server:v0.1
    container_name: minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/app/data
    networks:
      - external

networks:
  external:
   